/**
 * DO NOT EDIT THIS FILE
 * Playwright Configuration 
 * @file playwright.config.ts
 * @author : Mayureshwar Kadam
 * @description : This file contains the configuration for Playwright tests.
 * @requires path
 * @requires dotenv
 * @requires @playwright/test
 * @exports {import('@playwright/test').Config} 
 **/

import path from 'path';
import { defineConfig, devices, PlaywrightTestConfig } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve(__dirname, 'ENV.env') });

const uniqueId = new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }).replace(/[:/,\s]/g, '-');

const config: PlaywrightTestConfig = defineConfig({
  timeout: 10 * 15000,  // Global timeout for each test

  expect: {
    timeout: 30000,
  },

  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  //globalSetup: require.resolve('./global-setup'),    
  globalTeardown: './global-teardown.ts', 
  reporter: [
    ['html', { outputFolder: path.join(__dirname, 'Reports', `html-report-${uniqueId}`), open: 'never' }],
  ],

  use: {
    headless: true,
    trace: 'on',
    video: {
      mode: 'on',
      size: { width: 1920, height: 1080 },
    },
    screenshot: 'on',
    actionTimeout: 30000,
    deviceScaleFactor: undefined,
    viewport: null,
    launchOptions: {
      args: ['--start-maximized'],
      slowMo: 500,
    },
    baseURL: process.env.baseURL,
    storageState: 'auth.json', // Reuse the saved authentication state
  },

  workers: 10,

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        headless: false,
        trace: 'on',
        video: {
          mode: 'on',
          size: { width: 1920, height: 1080 },
        },
        screenshot: 'on',
        actionTimeout: 30000,
        deviceScaleFactor: undefined,
        viewport: null,
        
        launchOptions: {
          args: ['--start-maximized'],
          slowMo: 500,
        },
      },
    },
  ],

 
});

export default config;
