// import * as xlsx from 'xlsx';
// import * as fs from 'fs';
// import OpenAI from 'openai';
// import dotenv from 'dotenv';

// dotenv.config();

// const OPENAI_API_KEY = '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'; // Add your OpenAI API key to the .env file

// if (!OPENAI_API_KEY) {
//   throw new Error('OPENAI_API_KEY is not defined in the .env file.');
// }

// // Initialize OpenAI API
// const openai = new OpenAI({ apiKey: OPENAI_API_KEY });

// // Load the Excel sheet
// const workbook = xlsx.readFile('NRT.xlsx');
// const sheetName = workbook.SheetNames[0];
// const sheet = xlsx.utils.sheet_to_json(workbook.Sheets[sheetName]);

// // Generate test cases dynamically
// (async () => {
//   const prompt = `
//     You are an AI assistant. Generate Playwright test cases based on the following steps:
//     - Steps: ${JSON.stringify(sheet, null, 2)}
//     - Use Playwright's test framework and include proper assertions.
//   `;

//   try {
//     console.log('Sending prompt to OpenAI...');
//     const response = await openai.chat.completions.create({
//       model: 'gpt-3.5-turbo',
//       messages: [{ role: 'user', content: prompt }],
//       max_tokens: 1500,
//       temperature: 0.7,
//     });

//     const generatedTestCode = response.choices[0]?.message?.content?.trim();

//     if (!generatedTestCode) {
//       throw new Error('No test code was generated by OpenAI.');
//     }

//     // Save the generated test case to a file
//     const outputFilePath = './tests/generated-test.spec.ts';
//     fs.writeFileSync(outputFilePath, generatedTestCode);
//     console.log(`Test file successfully generated at: ${outputFilePath}`);
//   } catch (error) {
//     console.error('Error generating test cases:', error);
//   }
// })();
